
x-common: &common
  volumes:
    - "${PWD}:/opt/php-version-audit"
  working_dir: /opt/php-version-audit

services:
  composer:
    <<: *common
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.composer
    volumes:
    - "${PWD}:/opt/php-version-audit"
    - "${HOME}/.composer:/tmp"

  php:
    <<: *common
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    entrypoint: php
    environment:
      REQUIRE_VERSION_ARG: "false"

  php-version-audit:
    <<: *common
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    environment:
      REQUIRE_VERSION_ARG: "false"

  phpstan:
    <<: *common
    image: ghcr.io/phpstan/phpstan:1-php8.3
    command: analyse ./src

  alpine:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.alpine
    image: lightswitch05/php-version-audit:alpine

  bullseye:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.bullseye
    image: lightswitch05/php-version-audit:bullseye

  bookworm:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.bookworm
    image: lightswitch05/php-version-audit:bookworm
