FROM php:8.2-cli-bookworm
COPY --from=composer/composer:2.5-bin /composer /usr/bin/composer
RUN apt-get update && apt-get install -y libzip4 libzip-dev && docker-php-ext-install zip
ENTRYPOINT ["/usr/bin/composer"]
