#!/bin/bash

set -e

distroName=${DOCKERFILE_PATH##*.}

if [ "$distroName" == "alpine" ]; then
  docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:latest"
  docker push "${DOCKER_REPO}:latest"
fi

docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${distroName}"
docker push "${DOCKER_REPO}:${distroName}"
